#ifndef _Menu_Func_h
#define _Menu_Func_h

// Menu.c
#define MENU_INIT                   MENU_OFFSET | 0x01
#define MENU                        MENU_OFFSET | 0x02
#define DISPLAY_MENU_UPDATE         MENU_OFFSET | 0x03
#define DISPLAY_DATE_TIME_UPDATE    MENU_OFFSET | 0x04
#define DISPLAY_TEMP_UPDATE         MENU_OFFSET | 0x05
#define REGISTER_MENU_TEMP          MENU_OFFSET | 0x06
#define UNREGISTER_MENU_TEMP        MENU_OFFSET | 0x07
#define MENU_SEC_INT_CALLBACK       MENU_OFFSET | 0x08
#define FIND_MENU_STATE             MENU_OFFSET | 0x09

// MenuCallbacks.c
#define MENU_CALLBACKS_OFFSET                                             0x0100
#define POWER_KEY_CALLBACK          MENU_CALLBACKS_OFFSET | MENU_OFFSET | 0x0001
#define UP_KEY_CALLBACK             MENU_CALLBACKS_OFFSET | MENU_OFFSET | 0x0002
#define DOWN_KEY_CALLBACK           MENU_CALLBACKS_OFFSET | MENU_OFFSET | 0x0003
#define LEFT_KEY_CALLBACK           MENU_CALLBACKS_OFFSET | MENU_OFFSET | 0x0004
#define RIGHT_KEY_CALLBACK          MENU_CALLBACKS_OFFSET | MENU_OFFSET | 0x0005
#define ENTER_KEY_CALLBACK          MENU_CALLBACKS_OFFSET | MENU_OFFSET | 0x0006
#define CANCEL_KEY_CALLBACK         MENU_CALLBACKS_OFFSET | MENU_OFFSET | 0x0007
#define MENU_KEY_CALLBACK           MENU_CALLBACKS_OFFSET | MENU_OFFSET | 0x0008
#define EXIT_KEY_CALLBACK           MENU_CALLBACKS_OFFSET | MENU_OFFSET | 0x0009
#define NUM1_KEY_CALLBACK           MENU_CALLBACKS_OFFSET | MENU_OFFSET | 0x000A
#define NUM2_KEY_CALLBACK           MENU_CALLBACKS_OFFSET | MENU_OFFSET | 0x000B
#define NUM3_KEY_CALLBACK           MENU_CALLBACKS_OFFSET | MENU_OFFSET | 0x000C
#define NUM4_KEY_CALLBACK           MENU_CALLBACKS_OFFSET | MENU_OFFSET | 0x000D
#define NUM5_KEY_CALLBACK           MENU_CALLBACKS_OFFSET | MENU_OFFSET | 0x000E
#define NUM6_KEY_CALLBACK           MENU_CALLBACKS_OFFSET | MENU_OFFSET | 0x000F
#define NUM7_KEY_CALLBACK           MENU_CALLBACKS_OFFSET | MENU_OFFSET | 0x0010
#define NUM8_KEY_CALLBACK           MENU_CALLBACKS_OFFSET | MENU_OFFSET | 0x0011
#define NUM9_KEY_CALLBACK           MENU_CALLBACKS_OFFSET | MENU_OFFSET | 0x0012
#define NUM0_KEY_CALLBACK           MENU_CALLBACKS_OFFSET | MENU_OFFSET | 0x0013
#define VOL_UP_KEY_CALLBACK         MENU_CALLBACKS_OFFSET | MENU_OFFSET | 0x0014
#define VOL_DOWN_KEY_CALLBACK       MENU_CALLBACKS_OFFSET | MENU_OFFSET | 0x0015
#define CH_UP_KEY_CALLBACK          MENU_CALLBACKS_OFFSET | MENU_OFFSET | 0x0016
#define CH_DOWN_KEY_CALLBACK        MENU_CALLBACKS_OFFSET | MENU_OFFSET | 0x0017
#define MUTE_KEY_CALLBACK           MENU_CALLBACKS_OFFSET | MENU_OFFSET | 0x0018
#define MENU_CALLBACKS_INIT         MENU_CALLBACKS_OFFSET | MENU_OFFSET | 0x0019

// Menu_Time.c
#define MENU_TIME_OFFSET                                                         0x0200
#define MENU_SET_TIME                           MENU_TIME_OFFSET | MENU_OFFSET | 0x0001
#define MENU_TIME_UPDATE_DISP_PTR_POS           MENU_TIME_OFFSET | MENU_OFFSET | 0x0002
#define MENU_TIME_INCREMENT_PTR_POS_NUMBER      MENU_TIME_OFFSET | MENU_OFFSET | 0x0003
#define MENU_TIME_DECREMENT_PTR_POS_NUMBER      MENU_TIME_OFFSET | MENU_OFFSET | 0x0004
#define MENU_TIME_SET_PTR_POS_NUMBER            MENU_TIME_OFFSET | MENU_OFFSET | 0x0005

// Menu_Date.c
#define MENU_DATE_OFFSET                                                         0x0300
#define MENU_SET_DATE                           MENU_DATE_OFFSET | MENU_OFFSET | 0x0001
#define MENU_DATE_UPDATE_DISP_PTR_POS           MENU_DATE_OFFSET | MENU_OFFSET | 0x0002
#define MENU_DATE_INCREMENT_PTR_POS_NUMBER      MENU_DATE_OFFSET | MENU_OFFSET | 0x0003
#define MENU_DATE_DECREMENT_PTR_POS_NUMBER      MENU_DATE_OFFSET | MENU_OFFSET | 0x0004
#define MENU_DATE_SET_PTR_POS_NUMBER            MENU_DATE_OFFSET | MENU_OFFSET | 0x0005

// Menu_Switches.c
#define MENU_SWITCHES_OFFSET                                                     0x0400
#define SWITCHES_STATE_DISPLAY              MENU_SWITCHES_OFFSET | MENU_OFFSET | 0x0001
#define MENU_SWITCHES_SET                   MENU_SWITCHES_OFFSET | MENU_OFFSET | 0x0002
#define MENU_SWITCH_1_SET                   MENU_SWITCHES_OFFSET | MENU_OFFSET | 0x0003
#define MENU_SWITCH_2_SET                   MENU_SWITCHES_OFFSET | MENU_OFFSET | 0x0004
#define MENU_SWITCH_3_SET                   MENU_SWITCHES_OFFSET | MENU_OFFSET | 0x0005
#define MENU_SWITCH_4_SET                   MENU_SWITCHES_OFFSET | MENU_OFFSET | 0x0006
#define MENU_SWITCH_5_SET                   MENU_SWITCHES_OFFSET | MENU_OFFSET | 0x0007
#define MENU_SWITCH_6_SET                   MENU_SWITCHES_OFFSET | MENU_OFFSET | 0x0008
#define MENU_SWITCH_SET_UPDATE_DISPLAY      MENU_SWITCHES_OFFSET | MENU_OFFSET | 0x0009
#define MENU_SWITCH_SETTING                 MENU_SWITCHES_OFFSET | MENU_OFFSET | 0x000A
#define MENU_SWITCHES_SET_STRING            MENU_SWITCHES_OFFSET | MENU_OFFSET | 0x000B

// Menu_Switches_Set_Name.c
#define MENU_SWITCHES_SET_NAME_OFFSET                                                     0x0500
#define MENU_SWITCHES_SET_NAME              MENU_SWITCHES_SET_NAME_OFFSET | MENU_OFFSET | 0x0001
#define MENU_SWITCHES_SET_DISPLAY_STRING    MENU_SWITCHES_SET_NAME_OFFSET | MENU_OFFSET | 0x0002
#define MENU_SWITCH_NAME_SETTING            MENU_SWITCHES_SET_NAME_OFFSET | MENU_OFFSET | 0x0003
#define MENU_SWITCH_1_SET_NAME              MENU_SWITCHES_SET_NAME_OFFSET | MENU_OFFSET | 0x0004
#define MENU_SWITCH_2_SET_NAME              MENU_SWITCHES_SET_NAME_OFFSET | MENU_OFFSET | 0x0005
#define MENU_SWITCH_3_SET_NAME              MENU_SWITCHES_SET_NAME_OFFSET | MENU_OFFSET | 0x0006
#define MENU_SWITCH_4_SET_NAME              MENU_SWITCHES_SET_NAME_OFFSET | MENU_OFFSET | 0x0007
#define MENU_SWITCH_5_SET_NAME              MENU_SWITCHES_SET_NAME_OFFSET | MENU_OFFSET | 0x0008
#define MENU_SWITCH_6_SET_NAME              MENU_SWITCHES_SET_NAME_OFFSET | MENU_OFFSET | 0x0009
#define MENU_SW_NAME_UPDATE_DISP_PTR_POS    MENU_SWITCHES_SET_NAME_OFFSET | MENU_OFFSET | 0x000A
#define MENU_SWITCH_NAME_GET_NEXT_CHAR      MENU_SWITCHES_SET_NAME_OFFSET | MENU_OFFSET | 0x000B

// Menu_Switches_Dependency.c
#define MENU_SWITCHES_DEPENDENCY_OFFSET                                                     0x0600
#define MENU_SW_DEP_SET_NAME                MENU_SWITCHES_DEPENDENCY_OFFSET | MENU_OFFSET | 0x0001
#define MENU_SWITCH_1_DEPENDENCY_SET_FLAG   MENU_SWITCHES_DEPENDENCY_OFFSET | MENU_OFFSET | 0x0002
#define MENU_SWITCH_2_DEPENDENCY_SET_FLAG   MENU_SWITCHES_DEPENDENCY_OFFSET | MENU_OFFSET | 0x0003
#define MENU_SWITCH_3_DEPENDENCY_SET_FLAG   MENU_SWITCHES_DEPENDENCY_OFFSET | MENU_OFFSET | 0x0004
#define MENU_SWITCH_4_DEPENDENCY_SET_FLAG   MENU_SWITCHES_DEPENDENCY_OFFSET | MENU_OFFSET | 0x0005
#define MENU_SWITCH_5_DEPENDENCY_SET_FLAG   MENU_SWITCHES_DEPENDENCY_OFFSET | MENU_OFFSET | 0x0006
#define MENU_SWITCH_6_DEPENDENCY_SET_FLAG   MENU_SWITCHES_DEPENDENCY_OFFSET | MENU_OFFSET | 0x0007
#define MENU_SW_SET_EVENT_DISPLAY_STRING    MENU_SWITCHES_DEPENDENCY_OFFSET | MENU_OFFSET | 0x0008
#define MENU_EVENT_1_DEPENDENCY_SET_FLAG    MENU_SWITCHES_DEPENDENCY_OFFSET | MENU_OFFSET | 0x0009
#define MENU_EVENT_2_DEPENDENCY_SET_FLAG    MENU_SWITCHES_DEPENDENCY_OFFSET | MENU_OFFSET | 0x000A
#define MENU_EVENT_3_DEPENDENCY_SET_FLAG    MENU_SWITCHES_DEPENDENCY_OFFSET | MENU_OFFSET | 0x000B
#define MENU_EVENT_4_DEPENDENCY_SET_FLAG    MENU_SWITCHES_DEPENDENCY_OFFSET | MENU_OFFSET | 0x000C
#define MENU_SET_EVENT_STATE_DISPLAY_STRING MENU_SWITCHES_DEPENDENCY_OFFSET | MENU_OFFSET | 0x000D
#define MENU_EVENT_STATE_UPDATE_DISPLAY     MENU_SWITCHES_DEPENDENCY_OFFSET | MENU_OFFSET | 0x000E
#define MENU_EVENT_SET_STATE                MENU_SWITCHES_DEPENDENCY_OFFSET | MENU_OFFSET | 0x000F
#define MENU_EVENT_SET_DEPENDENCY           MENU_SWITCHES_DEPENDENCY_OFFSET | MENU_OFFSET | 0x0010
#define MENU_EVENT_SAVE                     MENU_SWITCHES_DEPENDENCY_OFFSET | MENU_OFFSET | 0x0011
#define MENU_SET_EVENT_SAVE_DISPLAY_STRING  MENU_SWITCHES_DEPENDENCY_OFFSET | MENU_OFFSET | 0x0012
#define MENU_SET_TIME_DEPENDENCY            MENU_SWITCHES_DEPENDENCY_OFFSET | MENU_OFFSET | 0x0013
#define MENU_SET_TEMP_DEPENDENCY            MENU_SWITCHES_DEPENDENCY_OFFSET | MENU_OFFSET | 0x0014
#define MENU_SET_TIME_TEMP_DEPENDENCY       MENU_SWITCHES_DEPENDENCY_OFFSET | MENU_OFFSET | 0x0015
#define MENU_SET_DEPENDENCY_DISPLAY_STRINGS MENU_SWITCHES_DEPENDENCY_OFFSET | MENU_OFFSET | 0x0016

#endif
