#ifndef _PWM_Backlight_Func_h
#define _PWM_Backlight_Func_h

// PWM_Backlight.c
#define PWM_BACKLIGHT_INIT                  PWM_BACKLIGHT_OFFSET | 0x01
#define SET_PWM_BACKLIGHT_INTENSITY         PWM_BACKLIGHT_OFFSET | 0x02
#define GET_PWM_BACKLIGHT_INTENSITY         PWM_BACKLIGHT_OFFSET | 0x03
#define CHANGE_PWM_BACKLIGHT_INTENSITY      PWM_BACKLIGHT_OFFSET | 0x04
#define CH_UP_KEY_CALLBACK                  PWM_BACKLIGHT_OFFSET | 0x05
#define CH_DOWN_KEY_CALLBACK                PWM_BACKLIGHT_OFFSET | 0x06

#endif
